name: Build xltui for Debian

on:
  workflow_dispatch:
    inputs:
      xltui_version:
        description: The version of xltui to build.
        type: string
        required: true
      build_version:
        description: The build version.
        type: string
        required: true
      architecture:
        description: Architecture to build (amd64, arm64, or 'all' for all architectures)
        type: choice
        default: 'all'
        options:
          - 'all'
          - 'amd64'
          - 'arm64'

permissions:
  contents: write

jobs:
  build-xltui:
    name: Build
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout xltui-debian
        uses: actions/checkout@v4

      - name: Build xltui
        run: ./build.sh ${{ inputs.xltui_version }} ${{ inputs.build_version }} ${{ inputs.architecture }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: xltui_*.deb


  release-xltui:
    name: (Draft-)Release xltui for Debian
    if: github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-xltui
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Publish Release Draft
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: xltui_*.deb
          name: ${{ inputs.xltui_version }}+${{ inputs.build_version }}
          tag_name: ${{ env.RELEASE_TAG }}
          fail_on_unmatched_files: true
